version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3020:3020"
    working_dir: /app
    restart: unless-stopped
