name: Campus Care Connect - CI

on:
  push:
    branches: [ "main" ]  # Runs when you push to main branch
  pull_request:
    branches: [ "main" ]  # Also runs when you open a pull request

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    name: Backend - Install Check
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Backend Dependencies
        run: npm install

  frontend-ci:
    runs-on: ubuntu-latest
    name: Frontend - Install and Build Check
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Frontend Dependencies
        run: npm install
      - name: Build Frontend
        run: npm run build
